spring:
  application:
    name: spring-redis-crac
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  cache:
    type: redis
    redis:
      time-to-live: 600000ms
      cache-null-values: false

server:
  port: 8080
  shutdown: graceful

# OpenAPI 3 / Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,caches
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cache: DEBUG
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev
  
  data:
    redis:
      host: localhost
      port: 6379 

logging:
  level:
    com.example.springrediscrac: DEBUG
    root: INFO

---
spring:
  config:
    activate:
      on-profile: test
  
  data:
    redis:
      host: localhost
      port: 6379 

logging:
  level:
    com.example.springrediscrac: DEBUG
    org.springframework.test: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

# Disable Swagger UI in production for security
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    com.example.springrediscrac: INFO
    root: WARN